### ISSUE TITLE
圣遗物生成指令失效

### ISSUE THREAD

**Issue by Emanoys** [jie65535/GrasscutterCommandGenerator#102]
在其他功能都正常的情况下，无论是否勾选“GC≥1.2.2”，都不能通过圣遗物选项卡生成圣遗物，查看控制台报错，内容为“java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.excels.ItemData.getItemType()" because "itemData" is null”

**Comment by jie65535** [comment]
请报告你使用的工具版本、服务端版本、生成的指令完整内容，完整的错误日志等信息以便于调试，谢谢。

**Comment by Emanoys** [comment]
工具版本：1.5.5
服务端版本：2.8.5
未勾选GC≥1.2.2时，指令“/giveart @123456 88514 15013 965004 965007 965002 964009 20”
错误日志内容
“> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.excels.ItemData.getItemType()" because "itemData" is null
        at emu.grasscutter.command.commands.GiveArtifactCommand.execute(GiveArtifactCommand.java:128)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:273)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:277)
        at emu.grasscutter.game.managers.chat.ChatManager.tryInvokeCommand(ChatManager.java:47)
        at emu.grasscutter.game.managers.chat.ChatManager.sendPrivateMessage(ChatManager.java:146)
        at emu.grasscutter.server.packet.recv.HandlerPrivateChatReq.handle(HandlerPrivateChatReq.java:18)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:244)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:71)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)”
勾选GC≥1,2,2时，指令“/give @123456 88514 lv20 15013 965004 965007 965002 965009”无错误日志，但是可莉回复“用法：give <玩家><物品ID|物品名>[数量][等级][精炼等级]”
辛苦大佬！

**Comment by jie65535** [comment]
这应该是魔改版的服务端，用法也许和官方版本不同？或者指定的圣遗物ID有问题？搞不清楚。

**Comment by Emanoys** [comment]
好的，明白了，谢谢！
