### ISSUE TITLE
无法连接本地服务器

### ISSUE THREAD

**Issue by ZXAS007** [jie65535/GrasscutterCommandGenerator#184]
发送验证码时提示未将对象引用设置到对象的实例

**Comment by jie65535** [comment]
请尽肯能提供更多信息以便于排查问题，包括但不限于服务端版本、客户端版本、插件版本，服务端日志和客户端错误信息等。
另发送验证吗需要玩家在线，以及服务器可以正确连通（正常查询到状态）。

**Comment by ZXAS007** [comment]
客户端版本是1.9.1服务端版本是2.0.0-unstable-e8cfc36插件版本是opencommand-for-unstable-1.5.2，在发送验证码时服务端会产生以下报错17:42:35 <ERROR:OpenCommandHandler> [OpenCommand] handler error.
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Integer (java.lang.Double and java.lang.Integer are in module java.base of loader 'bootstrap')
        at com.github.jie65535.opencommand.OpenCommandHandler.handle(OpenCommandHandler.java:61)
        at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
        at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:38)
        at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
        at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
        at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:57)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by jie65535** [comment]
你可以暂时先用控制台身份验证来使用远程执行，设置一个Token，重载一下配置。

**Comment by jie65535** [comment]
已经修复，请使用 v1.6.1 版本的 OpenCommand 插件：https://github.com/jie65535/gc-opencommand-plugin/releases/tag/v1.6.1

**Comment by WenBing2078** [comment]
![屏幕截图 2023-06-04 202533](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/cf62a231-cfae-4c63-858a-4c30bd514791)
v1.6.1 版本的 OpenCommand ，gc1.6.1

**Comment by ZXAS007** [comment]
😢

**Comment by jie65535** [comment]
感谢反馈，我更新了v1.6.1的发布，现在可以在下载试试。

**Comment by WenBing2078** [comment]
感谢您的工作，现在OpenCommand可以正常运行了
![屏幕截图 2023-06-04 203955](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/8fbd321f-2099-4e10-9e1c-642cde673d5f)
